import { defineEnableDraftMode } from 'next-sanity/draft-mode';
import { getSanityClient } from '@/content/sanity/client';
export async function GET(request: Request) {
  if (
    !process.env.SANITY_API_READ_TOKEN ||
    process.env.CONTENT_SOURCE === 'local'
  )
    return new Response(
      'Draft preview needs Sanity content mode and a Viewer token. See docs/CMS-GUIDE.md.',
      { status: 503 },
    );
  // Official helper validates the short-lived secret generated by authenticated Studio.
  return defineEnableDraftMode({
    client: getSanityClient().withConfig({
      token: process.env.SANITY_API_READ_TOKEN,
    }),
  }).GET(request);
}
